### ISSUE TITLE
Error in CMake  (Could NOT find XXXX)

### ISSUE THREAD

**Issue by jwhenry28** [unosviluppatore/antlr-cpp#2]
Hello! Thank you for the wonderful guide. I feel that I have a good grasp on how to write antlr grammars. However, I am having a really tough time getting started. When I run try to run cmake
on my machine in this repository, I get the following [error log](https://pastebin.com/RvMeZnTR).

I am still very new to Software Development, so please excuse me if this is a novice question. It looks like I have not installed certain necessary packages, but I am not sure where to begin. I tried following some of the links in the CMakeLists.txt file comments but was not able to discovery anything on my own. Thanks!

**Comment by gabriele-tomassetti** [comment]
Building C++ project can be quite complicated, so I understand the confusion. The error log you provided says that some libraries are missing, but the process to create the make/Visual Studio project has succeeded. In some C++ projects not all libraries are required, but they can be optional.

So the build step should work, have you tried if you can build the project?

**Comment by jwhenry28** [comment]
The build step is failing as well, here is the output: https://pastebin.com/mZuhH0bL

It may be that I am building incorrectly. My school only ever had us writing code in text editors and building via command line, so I am still trying to get the hang of IDEs. I just right clicked on the "antlr4-tutorial" target and clicked build, is that incorrect?

Clicking "Build" along the top of the window and selecting "Build Solution" fails as well, with a very similar error log. 

P.S. Thank you so much for the timely response!

**Comment by gabriele-tomassetti** [comment]
You are building correctly, you should build the `Antlr-cpp-tutorial.sln` project. The other one is just auto-generated by cmake.

The issue is that you do not have generated the parser and visitor with ANTLR. Or maybe you have generated them, but they are in the wrong place. 

This is what these errors are saying.
```
2>c1xx : fatal error C1083: Cannot open source file: 'C:\Users\jwhen\Desktop\Hacks\Tutorials\ANTLR\antlr-cpp-master\antlr4-runtime\SceneBaseVisitor.cpp': No such file or directory
2>c1xx : fatal error C1083: Cannot open source file: 'C:\Users\jwhen\Desktop\Hacks\Tutorials\ANTLR\antlr-cpp-master\antlr4-runtime\SceneVisitor.cpp': No such file or directory
2>c1xx : fatal error C1083: Cannot open source file: 'C:\Users\jwhen\Desktop\Hacks\Tutorials\ANTLR\antlr-cpp-master\antlr4-runtime\SceneParser.cpp': No such file or directory
2>c1xx : fatal error C1083: Cannot open source file: 'C:\Users\jwhen\Desktop\Hacks\Tutorials\ANTLR\antlr-cpp-master\antlr4-runtime\SceneLexer.cpp': No such file or directory
```

Can you see any of these files `SceneLexer.cpp`, `SceneParser.cpp`, etc. inside the folder `antlr4-runtime`?

If you cannot see them, first you have to make sure that you have setup ANTLR. You can follow the [setup section in the article](https://tomassetti.me/getting-started-antlr-cpp/) to do that.

If ANTLR is setup correctl,y you should generate the parser, with the following command. The command should be launched in the folder where the file `Scene.g4` is.

```
antlr4 -Dlanguage=Cpp -no-listener -visitor -o antlr4-runtime Scene.g4
```

Hopefully then the build should succeed.

**Comment by jwhenry28** [comment]
Ah yes, I originally was running the tutorial in Visual Studio Code (where I have the ANTLR extension), but switched over to Visual Studio 2019 so I forget that I now have to run the batch command from the terminal. That helped, but I am now getting this error: https://pastebin.com/Y6ShgYLS

I do not have access to a 32 bit machine, is there any way to specify the build to run on a 64 bit?

**Comment by gabriele-tomassetti** [comment]
It's true that modern computers have all 64-bit, but you can still compile for 32-bit programs. In fact, this is usually the default compilation target. This is because many libraries (including the ANTLR runtime) do not come in 64-bit. Most programs simply do not need more memory than the one you get with 32-bit.

In fact 32-bit should be the default target created by the project. This is how it appears on Visual Studio on my machine.
![immagine](https://user-images.githubusercontent.com/12112299/78967580-2ab75e00-7b03-11ea-9ba5-8159450c4e5e.png)
Can you see if you can select as platform/architecture Win32 (or x86)?

This may not work if all the other libraries in your machine are only in 64-bit, but this is usually not the case. Usually you install both the x86/32-bit and x64/64-bit if they are available.

**Comment by jwhenry28** [comment]
Yes, I still am having the same error. I also tried every solution mentioned [here](https://stackoverflow.com/questions/3563756/fatal-error-lnk1112-module-machine-type-x64-conflicts-with-target-machine-typ) with no avail. Although I could not find the Platform dropdown under VC++ Directories (I have something called VC++ Project Settings). Additionally, I tried the steps mentioned [here](https://stackoverflow.com/questions/37675012/project-not-selected-to-build-for-this-solution-configuration) but was unable to select the Deploy box (it is grayed out). My configuration manager looks like the original poster's in that stackoverflow post.

**Comment by gabriele-tomassetti** [comment]
Sorry, I don't understand if you were able to select the Win32 platform.

![immagine](https://user-images.githubusercontent.com/12112299/79008412-a3e39f00-7b5d-11ea-96ba-220bdfd3cc72.png)

Ignore the interface in Italian. Which platform is selected for your project?

You can read the management of configuration by clicking on the down arrow in the menu bar.

![immagine](https://user-images.githubusercontent.com/12112299/79008536-e6a57700-7b5d-11ea-8733-332fb15a2b05.png)

**Comment by jwhenry28** [comment]
Yes, I could select Win32, althuogh it is only an option for antlr4-tutorial and not ALL_BUILD or ZERO_CHECK. Additionally, when making the Win32 config there was no option except "copy settings from x64". Is that a problem?

![image](https://user-images.githubusercontent.com/48418211/79009269-bf7e8380-7b24-11ea-9c98-203dabdd8f1a.png)

![image](https://user-images.githubusercontent.com/48418211/79009313-cefdcc80-7b24-11ea-814c-c318da7295b2.png)

**Comment by gabriele-tomassetti** [comment]
> Additionally, when making the Win32 config there was no option except "copy settings from x64". Is that a problem?

In theory that should not be a problem because Visual Studio should be smart enough to copy the setting, but also to update them correctly for target type. 

I still do not understand why the project was generated with the wrong target architecture, considering that by default it should be x86/win32.

I am running out of ideas. You could try looking if Properties -> Linker -> All options you see this option:

![immagine](https://user-images.githubusercontent.com/12112299/79038430-80f6d080-7bd9-11ea-8cb5-533f5088f778.png)

Apart from this, you could also try to simply create a new C++ in Visual Studio. Then you add the antlr-runtime library and the source files manually and see if you can build them. We used cmake to allow easy cross-platform support, but it is just C++ code.
